### ISSUE TITLE
[feat] Hide nvim-tree window when opening

### ISSUE THREAD

**Issue by carlosflorencio** [shortcuts/no-neck-pain.nvim#133] opened 2023-01-10 19:25 UTC
## Describe the problem

It would be nice to have a config to close the `nvim-tree` window on startup, and re-enable `nvim-tree` on exit.

Video showing the current behaviour:

https://user-images.githubusercontent.com/1500881/211642920-8e0230a6-5fe8-49e5-afbb-387273b0ac20.mp4

When starting NNP, the `nvim-tree` is still open and using horizontal space.

Thanks for the plugin btw :).

**Comment by shortcuts** [comment] 2023-01-10 20:21
Hey, thanks for opening the issue!

Indeed we will always add the side buffers on each side of the window (as per https://github.com/shortcuts/no-neck-pain.nvim/pull/126), can you confirm that opening NNP without the side tree opened, and then opening it works correctly?

**Comment by shortcuts** [comment] 2023-01-10 20:25
The most obvious solution to me is:
1. when enabling NNP, if a side-tree is opened
2. register it in the internal state
3. close it
4. enable
5. re-open side tree

we can make 5. configurable as per your suggestion

**Comment by carlosflorencio** [comment] 2023-01-11 09:22
> Hey, thanks for opening the issue!
> 
> Indeed we will always add the side buffers on each side of the window (as per #126), can you confirm that opening NNP without the side tree opened, and then opening it works correctly?

Yep, works correctly starting with the side tree closed.



> The most obvious solution to me is:
> 
> 1. when enabling NNP, if a side-tree is opened
> 2. register it in the internal state
> 3. close it
> 4. enable
> 5. re-open side tree
> 
> we can make 5. configurable as per your suggestion

Maybe make 3. configurable as well for maximum flexibility? :)

**Comment by shortcuts** [comment] 2023-01-11 18:55
Yup exactly, I think I have a decent solution, will push the fix soon so you can try it :D

**Comment by shortcuts** [comment] 2023-01-13 23:07
Hey, the feat have been merged to main, don't hesitate to try it and let me know!

**Comment by carlosflorencio** [comment] 2023-01-15 12:29
Hey @shortcuts, thanks for the work on this!

Unfortunately, the behaviour doesn't seem to be working? Because with the following config (in the print), `nvim-tree` is still open but now stays on the far left and the center buffer has reduced width:
<img width="1704" alt="image" src="https://user-images.githubusercontent.com/1500881/212540640-f377771f-16a3-4c85-999b-8abfd328cf38.png">

**Comment by shortcuts** [comment] 2023-01-15 13:21
## When toggling the tree with NNP already enabled

<img width="1280" alt="Screenshot 2023-01-15 at 14 19 29" src="https://user-images.githubusercontent.com/20689156/212542996-cfeadbdc-57df-4309-abcf-679d8bb18861.png">

## When enabling NNP the tree opened

<img width="1280" alt="Screenshot 2023-01-15 at 14 20 23" src="https://user-images.githubusercontent.com/20689156/212543047-53dda379-838b-432c-84f3-508526987c25.png">

------

I get the expected result, could you please provide steps to reproduce?

**Comment by carlosflorencio** [comment] 2023-01-15 19:18
The scenario:
- `nvim-tree` and a file buffer opened
- Running `:NoNeckPain`
I'd expect the `nvim-tree` buffer to be closed when enabling NNP, but instead, it stays opened in the left.


https://user-images.githubusercontent.com/1500881/212562311-3c745675-016a-47b1-9da5-66bef5f272c8.mp4

**Comment by shortcuts** [comment] 2023-01-15 19:53
Thanks a lot for the recording!

> 'd expect the nvim-tree buffer to be closed when enabling NNP, but instead, it stays opened in the left.

To do so, providing `reopen = false` should do it.

```lua
require("no-neck-pain").setup({
    -- your other options...
    integrations = {
        NvimTree = {
            reopen = false, -- this tells the plugin to not reopen the tree if we close it
        },
    },
})
```

however, it seems that there's still an issue with the size of the left buffer, will investigate!

**Comment by shortcuts** [comment] 2023-01-15 20:00
following in https://github.com/shortcuts/no-neck-pain.nvim/issues/142

**Closed by shortcuts** 2023-01-15 20:00 UTC
Labels: enhancement, in progress

**Comment by carlosflorencio** [comment] 2023-01-15 20:08
Having `reopen = false` correctly closes the `nvim-tree` when starting NPP yes, but two things:
- The buffer has the wrong width (you already noticed yep)
- When closing NPP, the `nvim-tree` doesn't open again (to kind of restore the old window state before entering NPP)

Video:
https://user-images.githubusercontent.com/1500881/212564305-94b30c00-430b-48fc-bfe1-8b4374405933.mp4

Changing close to false:
- The `nvim-tree` is open in the centered buffer.

**Comment by shortcuts** [comment] 2023-01-15 20:41
thanks again for the reporting!

https://github.com/shortcuts/no-neck-pain.nvim/pull/144 should've fix the width issue

**Comment by carlosflorencio** [comment] 2023-01-16 10:04
The width fix works :).

The current behaviour is:
- `reopen = false`: nvim-tree closes when starting NNP (correct) but doesn't reopen when exiting NPP (correct).
- `reopen = true`: nvim-tree stays open (far left, center buffer has reduced width) when starting NNP (**wrong**), keeps nvim-tree open when exiting NPP (correct).

**Comment by shortcuts** [comment] 2023-01-16 10:34
Thanks for testing!! I still wonder why I'm not able to reproduce the width issue on my end when reopen = true, I'll try on larger screens etc.
