### ISSUE TITLE
layout is broken when i open a file with nvim tree

### ISSUE THREAD

**Issue by sand4rt** [shortcuts/no-neck-pain.nvim#252] opened 2023-10-20 11:04 UTC
## Description

When i open a file through nvim-tree my layout gets messed up

## Steps to reproduce

1. enable no-neck-pain
2. open nvim-tree
3. open a file

![ezgif-3-6b2e532147](https://github.com/shortcuts/no-neck-pain.nvim/assets/17591696/9881ded5-5f84-4d2f-821e-be3964b400c5)

config _(setting the width seems to cause the problem)_:

```lua
require("no-neck-pain").setup({
    width = 154,
    autocmds = {
        enableOnVimEnter = false,
    },
    mappings = {
        enabled = false,
    },
    integrations = {
        NvimTree = {
            position = "left",
            reopen = true,
        },
        undotree = {
            position = "left",
        },
        neotest = {
            position = "right",
            reopen = true,
        },
    },
})
```

## Expected behavior

The no-neck-pain layout should persist

## Environment

- Neovim version: latest
- no-neck-pain.nvim version: 1.3.0
- Plugin clash: nvim-tree

**Comment by shortcuts** [comment] 2023-10-20 19:20
Hey thanks! it looks like there's not enough remaining space to have an NNP buffer + the tree, if you set `minSideBufferWidth = 0` at the root of the options, does it still doesn't open it?

**Comment by sand4rt** [comment] 2023-10-20 19:37
Hi, thanks for your reply. Just tried it but it has no effect.

**Comment by shortcuts** [comment] 2023-10-20 20:30
ah but keys in lua are case sensitive, so you need to follow what's defined in https://github.com/shortcuts/no-neck-pain.nvim#-configuration

**Comment by sand4rt** [comment] 2023-10-20 20:40
> ah but keys in lua are case sensitive, so you need to follow what's defined in https://github.com/shortcuts/no-neck-pain.nvim#-configuration

Oops, copied the wrong config over to Github _(i adjusted my previous message/config)_. The issue still persist after fixing the casing.

**Comment by shortcuts** [comment] 2023-10-24 21:15
hey, reproduced and fixed in https://github.com/shortcuts/no-neck-pain.nvim/pull/250

**Closed** 2023-10-24 21:49 UTC
Labels: bug, in progress
