### ISSUE TITLE
[bug] buftype incorrectly set for scratch pad

### ISSUE THREAD

**Issue by embe221ed** [shortcuts/no-neck-pain.nvim#295] opened 2024-01-26 12:39 UTC
## Description

The `:set buftype` command returns `buftype=nofile` for scratch pads. This makes it impossible to save the scratch pad's buffer content.

## Steps to reproduce

1. enable scratch pad
2. run `NoNeckPain`
3. go to one of the scratch pads and run `set buftype` or try to `:w`

## Expected behavior

the `buftype` should be set to empty string, and it is done at the end of initialization, however for some reason it does not work.

## Environment

- Neovim version: [Nightly]
- no-neck-pain.nvim version: [latest]

**Comment by danymat** [comment] 2024-02-04 15:41
Hello, I get the same issue: saving in scratchpad does not work, possibly for this very reason

**Comment by danymat** [comment] 2024-02-04 15:47
Hello, it seems like new #291 PR change did indeed use a new function, breaking the save feature: 

https://github.com/shortcuts/no-neck-pain.nvim/blame/3005aecdd3fabc13a170357d5347a6cc2199ab26/lua/no-neck-pain/wins.lua#L91

**Comment by embe221ed** [comment] 2024-02-04 16:52
> Hello, it seems like new #291 PR change did indeed use a new function, breaking the save feature:
> 
> https://github.com/shortcuts/no-neck-pain.nvim/blob/3005aecdd3fabc13a170357d5347a6cc2199ab26/lua/no-neck-pain/wins.lua#L91

I think the changes in the mentioned PR may have caused the issue, but the actual reason is that this PR **fixed** setting the options for scratch pad. I don't think that changing the functions is an actual reason.
Basically, when it comes to the scratch pad, it should have `buftype` option set to another value, which will resolve the issue.

**Comment by shortcuts** [comment] 2024-02-04 17:17
Hey there, thanks for using the plugin and reporting the issue!

I can confirm there is an issue and it's mostly caused because of the option definition order, it should be fixed in https://github.com/shortcuts/no-neck-pain.nvim/pull/300

**Closed** 2024-02-04 17:17 UTC

**Comment by shortcuts** [comment] 2024-02-04 17:19
fix released in 1.8.0! thanks again :D

**Comment by danymat** [comment] 2024-02-05 08:29
Thanks for the quick fix !! Will try it out :)
