### ISSUE TITLE
Massive memory leak on Windows after using Telescope find_files/oldfiles/git_files with no-neck-pain installed

### ISSUE THREAD

**Issue by Strus** [shortcuts/no-neck-pain.nvim#171] opened 2023-02-07 17:44 UTC
## Steps to reproduce

1. Install and setup Telescope and no-neck-pain
2. Open any file from a git repository in neovim
3. Open Windows task manager, find nvim.exe and observe memory consumption
4. Repeat the sequence:

- open oldfiles Telescope picker
- open find_files Telescope picker
- open oldfiles Telescope picker
- open git_files Telescope picker

After a few repeats Neovim memory will jump significantly, and will increase logarithmically every time Telescope picker is opened. Memory is never freed.

Take into account that it reproduces with no-neck-pain just installed and set up, without actually enabling it in the buffer.

I stop reproducing that after I remove no-neck-pain, without changing anything else in the config, Then I enabled it again, and was able to reproduce the bug.

Unfortunately I didn't have time to test that with minimal config or on macOS, I can try that in the following days if you won't be able to reproduce.

## Expected behavior

No memory leak.

## Environment

- Neovim version: Nightly
- no-neck-pain.nvim version: latest stable
- Plugin clash: Telescope oldfiles/find_files/git_files pickers. Maybe some others, but I got the 100% repro with that ones.

**Comment by shortcuts** [comment] 2023-02-07 20:20
Hey, thanks for reporting!

I'm not able to reproduce as I'm not on Windows, but will try the following on MacOS!

**Comment by shortcuts** [comment] 2023-02-07 20:37
It doesn't seem to do anything on MacOS, I tried the sequence ~20 times and still at 0.9% of memory. Could you please let me know if you open the files or something? Or maybe do a small video if possible? Thanks!

**Comment by shortcuts** [comment] 2023-02-26 18:01
closing the issue as it have been stalled for some time, feel free to re-open if necessary!

**Closed by shortcuts** 2023-02-26 18:01 UTC
Labels: need investigation, not confirmed
