### ISSUE TITLE
Jumps around when being used with nvim-tree

### ISSUE THREAD

**Issue by cloudlena** [shortcuts/no-neck-pain.nvim#77] opened 2022-12-19 09:27 UTC
## Description

When using this plugin with pseudo buffers like [nvim-tree](https://github.com/nvim-tree/nvim-tree.lua), the focused buffer jumps around.

## Steps to reproduce

1. Install this plugin and `nvim-tree`
1. Run `:NoNeckPain`
1. Run `:NvimTreeToggle`
1. The focused buffer jumps around

### Without nvim-tree

<img width="1920" alt="Screenshot 2022-12-19 at 12 10 13" src="https://user-images.githubusercontent.com/6780471/208413259-916f2be0-6abc-44fe-85f2-2e921b9819be.png">

### With nvim-tree

<img width="1920" alt="Screenshot 2022-12-19 at 12 10 32" src="https://user-images.githubusercontent.com/6780471/208413287-6bc7b55e-8a2e-4fed-9212-96eaeed12b30.png">

## Expected behavior

I would expect the focused buffer to stay in place when the only other buffer opened is a pseudo buffer like `nvim-tree` and they both fit next to each other without any jumping around.

The current behavior is even weirder for me when using something like [symbols-outline](https://github.com/simrat39/symbols-outline.nvim).

## Environment

- Neovim: 0.8.x
- Plugin clash: nvim-tree

**Comment by shortcuts** [comment] 2022-12-19 09:29
Hey @cloudlena, thanks for opening the issue! I'll definitely take a look at it asap

Would you mind adding a screenshot or two so I can better reproduce?

**Comment by cloudlena** [comment] 2022-12-19 11:12
Thanks for the quick reply, @shortcuts!
I added some screenshots to the issue above.

**Comment by shortcuts** [comment] 2022-12-19 12:24
> I added some screenshots to the issue above.

Thanks! Helps a lot. I assume it's either VimResized that closes the side buffer, or NNP getting disabled in the WinEnter hook

Will investigate!

**Comment by shortcuts** [comment] 2022-12-19 23:23
Hey there, if you don't mind testing, I've merged a fix that should fix the buffer position :)

**Comment by shortcuts** [comment] 2022-12-19 23:24
I've added screenshots in the PR if that helps

Thanks again for the issue!

**Closed** 2022-12-19 23:24 UTC
Labels: bug, in progress

**Comment by cloudlena** [comment] 2022-12-20 09:22
Now it just jumps a tiny bit, which is negligible. Thanks a lot for the quick fix, @shortcuts!

**Comment by shortcuts** [comment] 2022-12-20 09:24
> Now it just jumps a tiny bit, which is negligible. Thanks a lot for the quick fix, @shortcuts!

Yup I did not found a way to prevent the small UI shift, I believe it's because all buffer push each other when the tree opens. I'll still investigate!
