### ISSUE TITLE
NNP is not enabled when running :checkhealth

### ISSUE THREAD

**Issue by sand4rt** [shortcuts/no-neck-pain.nvim#367] opened 2024-05-30 23:42 UTC
## Description

NNP is not enabled when running `:checkhealth`

## Steps to reproduce

1. I did the command `:checkhealth`
2. Then I saw that NNP is not enabled

## Expected behavior

NNP should be enabled when running `:checkhealth`

## Environment

- Neovim version: 0.10.0
- no-neck-pain.nvim version: latest

**Comment by shortcuts** [comment] 2024-05-31 07:53
Hey @sand4rt, thanks for opening the issue! I'm not sure what should NNP report as there's no external dependencies, maybe it could be great to do an assertion of the user config in order to report usage of deprecated/unknown options?

Let me know if you have any use cases in mind

**Comment by sand4rt** [comment] 2024-05-31 10:25
Hi @shortcuts, thanks for the reply. The issue is not about the NNP `checkhealth` results/reports. It is that the NNP side windows are not enabled there

**Comment by shortcuts** [comment] 2024-05-31 10:43
Ahhhh ok sorry I misunderstood, weirdly with one side opened only I did not noticed it, I'll try with both!

**Comment by shortcuts** [comment] 2024-06-02 07:49
Hey! So I just tried it and the reason why it works for me is because I have `autocmds.enableOnTabEnter` set to `true`, not sure if you do too. As `checkhealth` runs in its own tab, it is required for it to work

**Comment by shortcuts** [comment] 2024-06-02 07:52
Makes me think that for simplicity, I should default `enableOnTabEnter` if `enableOnVimEnter` is `true`, as the behavior should stay consistent

**Comment by sand4rt** [comment] 2024-06-02 09:26
> Hey! So I just tried it and the reason why it works for me is because I have `autocmds.enableOnTabEnter` set to `true`, not sure if you do too. As `checkhealth` runs in its own tab, it is required for it to work

Thanks for the reply! Ah, NNP is enabled now when `autocmds.enableOnTabEnter = true` is set! It's kind of slow, though, because `:checkhealth` runs first before NNP kicks in. I also noticed that Neovim closes completely when I use `:q` in a separate `:checkhealth` tab while NNP is enabled _(it should only close the `:checkhealth` tab)_.

> Makes me think that for simplicity, I should default enableOnTabEnter if enableOnVimEnter is true, as the behavior should stay consistent

That sound reasonable to me, but im also fine with adding the additional `autocmds.enableOnTabEnter = true`.

**Comment by shortcuts** [comment] 2024-06-02 09:41
> I also noticed that Neovim closes completely when I use `:q` in a separate `:checkhealth` tab while NNP is enabled _(it should only close the `:checkhealth` tab)_.

looks like what I observed here https://github.com/shortcuts/no-neck-pain.nvim/issues/361#issuecomment-2120026847, it's fixed in the next major but I'll fix it here too indeed

**Comment by shortcuts** [comment] 2024-08-29 22:14
Hey there, hope you are doing well

This should be fixed in 1.15.0! https://github.com/shortcuts/no-neck-pain.nvim/pull/378

**Closed by shortcuts** 2024-08-29 22:14 UTC
Labels: enhancement, help wanted, need investigation

**Comment by shortcuts** [comment] 2024-08-30 13:13
> Hi @shortcuts, there are a lot of things broken now unfortunately, when i `:q` inside `:checkhealth`, the side buffers remain open:

> Also when i open neotree, when NNP enabled, NNP gets closed

hey!

could you share your config please? I'm not able to reproduce any of the issue

**Comment by sand4rt** [comment] 2024-08-30 13:23
Sure, let me know if you need more info!:

```lua
return {
    "shortcuts/no-neck-pain.nvim",
    version = "*",
    lazy = false,
    keys = {
        { "<Leader>z", "<cmd>:NoNeckPain<CR>", noremap = true, silent = true },
    },
    opts = {
        width = 148,
        autocmds = {
            enableOnTabEnter = true,
            skipEnteringNoNeckPainBuffer = true,
        },
        mappings = {
            enabled = false,
        },
        integrations = {
            NeoTree = {
                position = "left",
                reopen = true,
            },
            undotree = {
                position = "left",
            },
            neotest = {
                position = "right",
                reopen = true,
            },
            TSPlayground = {
                position = "right",
                reopen = true,
            },
            NvimDAPUI = {
                position = "right",
                reopen = true,
            },
        },
    },
}
```

**Comment by shortcuts** [comment] 2024-08-30 13:30
(reproducing from https://github.com/shortcuts/no-neck-pain.nvim/pull/383)

do you use nvim <0.10 by any chance?

**Comment by sand4rt** [comment] 2024-08-30 13:57
i'm using 0.10.1

**Comment by shortcuts** [comment] 2024-08-30 14:00
ok so that's an other issue then ahah

I'm still unable to reproduce on 0.10.1 🤔

**Comment by sand4rt** [comment] 2024-08-30 14:44
> when i `:q` inside `:checkhealth`, the side buffers remain open

@shortcuts 
Just tested it again and this does not happen when i disable all my plugins tough. `:checkhealth` takes a few sec to load when i enable all my plugins. Maybe that is related to the issue?

the other issue, where NNP closes when i open neotree is consistent, even when i have all my config disabled

**Comment by sand4rt** [comment] 2024-08-30 18:22
> when i `:q` inside `:checkhealth`, the side buffers remain open

@shortcuts Thanks! I discovered that the issue only occurs when i access `:checkhealth` through [Telescope cmdline](https://github.com/jonarrien/telescope-cmdline.nvim). _(I have this remap: `{ ":", "<cmd>Telescope cmdline<CR>", desc = "telescope: cmdline" }`)_

**Comment by shortcuts** [comment] 2024-08-30 22:36
<img width="1512" alt="Screenshot 2024-08-31 at 00 33 22" src="https://github.com/user-attachments/assets/e684a3f5-6d30-4ed4-811e-b164dc62c52b">

I can only try on my laptop right now but if there's enough space for neotree and nnp to live (here the width is 30), it seems to behave correctly.

Could you please let me know the number of columns in your ui? (`:lua vim.print(vim.o.columns)` so I can try to create a test case with similar setup as yours

**Comment by sand4rt** [comment] 2024-08-30 22:49
> I can only try on my laptop right now but if there's enough space for neotree and nnp to live (here the width is 30), it seems to behave correctly.

Yeah, this also works fine on my machine.


> Could you please let me know the number of columns in your ui? (:lua vim.print(vim.o.columns) so I can try to create a test case with similar setup as yours

:lua vim.print(vim.o.columns) = 240

**Comment by shortcuts** [comment] 2024-09-03 19:10
hey @sand4rt, others have reported this issue too https://github.com/shortcuts/no-neck-pain.nvim/issues/389, I fixed it in `next` I believe!

**Comment by sand4rt** [comment] 2024-09-03 19:12
@shortcuts thanks! I'll try it later on!
