### ISSUE TITLE
NNP no longer opens on empty buffer.

### ISSUE THREAD

**Issue by vinoff** [shortcuts/no-neck-pain.nvim#392] opened 2024-09-07 10:28 UTC
NNP no longer opens on an empty buffer on my side. Can anyone reproduce? It used to open.

Just do "nvim" without a given file.

Here is my config:

```
return {
	"shortcuts/no-neck-pain.nvim",
	config = function()
		require("no-neck-pain").setup({
			-- width of the main focused window
			fallbackOnBufferDelete = true,
			width = 100,
			autocmds = {
				enableOnVimEnter = true,
				enableOnTabEnter = true,
				skipEnteringNoNeckPainBuffer = true,
			},
			buffers = {
				colors = {
					background = "#000000",
				},
				right = {
					enabled = false,
				},
			},
		})
	end,
}
```

**Comment by shortcuts** [comment] 2024-09-08 18:21
Hey @vinoff thanks for the issue! I'm not able to reproduce personally, do you have any dashboard plugins or things like that alters the nvim opening?

**Comment by vinoff** [comment] 2024-09-08 18:39
Not really.. I haven't added any plugins recently and it used to work correctly. On your side, NNP opens even when when not opening a file? When opening a file (`nvim test.md`) NNP functions correctly. Doing `nvim` only, NNP doesn't open.

**Comment by vinoff** [comment] 2024-09-08 18:48
Doing `:NoNeckPain` or `:NoNeckPainToggleLeftSide` also don't work..

**Comment by shortcuts** [comment] 2024-09-08 20:30
Hey @vinoff, adding `lazy = false` to the config seems to fix the issue, however I'm not sure what changed on the lazy.nvim side 🤔

**Comment by shortcuts** [comment] 2024-09-08 20:32
I can also confirm this doesn't work without `lazy = false` in older version of the plugin, so I think something changed either on your config (e.g. your removed the `lazy` line), or on the `lazy.nvim` side

**Comment by shortcuts** [comment] 2024-09-08 20:33
(Closing since it's not a bug on the plugin side but feel free to keep commenting, and thanks for using the plugin :D)

**Closed by shortcuts** 2024-09-08 20:33 UTC
Labels: need investigation, not confirmed

**Comment by vinoff** [comment] 2024-09-09 09:30
Adding that to my config doesn't fix the issue @shortcuts. Am I missing something?

```
return {
	"shortcuts/no-neck-pain.nvim",
	lazy = false,
	config = function()
		require("no-neck-pain").setup({
			-- width of the main focused window
			fallbackOnBufferDelete = true,
			width = 100,
			autocmds = {
				enableOnVimEnter = true,
				enableOnTabEnter = true,
				skipEnteringNoNeckPainBuffer = true,
			},
			buffers = {
				colors = {
					background = "#000000",
				},
				right = {
					enabled = false,
				},
			},
		})
	end,
}
```

**Comment by vinoff** [comment] 2024-09-09 09:35
@shortcuts, using an older version does indeed seem to fix the issue:

I am using tag/version 1.9.0 and it is working correctly..

```
return {
	"shortcuts/no-neck-pain.nvim",
	-- lazy = false,
	-- enabled = false,
	version = "v1.9.0",
	tag = "v1.9.0",
	config = function()
		require("no-neck-pain").setup({
			-- width of the main focused window
			fallbackOnBufferDelete = true,
			width = 100,
			autocmds = {
				enableOnVimEnter = true,
				enableOnTabEnter = true,
				skipEnteringNoNeckPainBuffer = true,
			},
			buffers = {
				colors = {
					background = "#000000",
				},
				right = {
					enabled = false,
				},
			},
		})
	end,
}
```

**Comment by vinoff** [comment] 2024-09-10 12:21
More info:

version - 1.15 ---> WORKS.
version - 1.16 ---> DOES NOT WORK.
